<?php

namespace App\Services;

use App\Models\Order;
use App\Models\Product;
use App\Models\Report;
use App\Models\OffPlatformWarning;
use App\Models\User;

class SellerTrustService
{
    /**
     * Builds a deterministic, rule-based trust profile for a seller.
     * Every number here comes from a real query — nothing is estimated or
     * generated by AI. This is intentional: a wrong trust score is a much
     * worse failure than a wrong chat answer, since it's a factual claim
     * about someone's money-handling history.
     */
    public function build(User $seller): array
    {
        $completedOrders = Order::where('seller_id', $seller->id)
            ->whereIn('status', ['delivered', 'returned'])
            ->count();

        $returnedOrders = Order::where('seller_id', $seller->id)
            ->where('status', 'returned')
            ->count();

        // NOTE: 'returned' is a valid order status in the schema, but nothing
        // in the app currently transitions an order into it — so this will
        // read 0% for every seller until a returns workflow exists. Left in
        // deliberately so the score picks it up automatically once that's built.
        $returnRate = $completedOrders > 0
            ? round(($returnedOrders / $completedOrders) * 100, 1)
            : 0.0;

        $totalOrdersAllTime = Order::where('seller_id', $seller->id)
            ->whereNotNull('paid_at')
            ->where('status', '!=', 'refunded')
            ->count();

        $reports30d = (int) Report::where('reported_id', $seller->id)
            ->where('created_at', '>=', now()->subDays(30))
            ->sum('report_count');

        $reportsAllTime = (int) Report::where('reported_id', $seller->id)->sum('report_count');

        $lastReportAt = Report::where('reported_id', $seller->id)
            ->latest('created_at')
            ->value('created_at');

        $continuedWarnings = OffPlatformWarning::where('seller_id', $seller->id)
            ->where('action', 'continued')
            ->count();

        $avgRating    = (float) ($seller->avg_rating ?? 0);
        $totalReviews = (int) ($seller->total_reviews ?? 0);

        $monthsSinceJoin = $seller->created_at ? $seller->created_at->diffInMonths(now()) : 0;

        // ── Deterministic score, 0–10 ─────────────────────────────────────
        $score = 5.0;
        $score += $avgRating > 0 ? ($avgRating - 3) * 1.0 : 0;                 // rating: -2..+2
        $score += $seller->is_verified ? 0.5 : ($seller->hasActiveSubscription() ? 0.25 : 0);
        $score += min(1.0, $monthsSinceJoin / 24);                             // tenure: up to +1 over 2yrs
        $score += $totalOrdersAllTime > 0
            ? min(1.0, log10($totalOrdersAllTime + 1) / log10(101))            // volume: up to +1 near 100 orders
            : 0;
        $score -= min(2.0, $reports30d * 0.5);                                 // recent reports: up to -2
        $score -= min(2.0, $continuedWarnings * 0.4);                          // off-platform pushiness: up to -2
        $score -= min(2.0, $returnRate * 0.05);                                // returns: up to -2
        $score = max(0.0, min(10.0, round($score, 1)));

        $highRisk = $seller->is_flagged_for_review
            || $reports30d >= 3
            || $returnRate > 15
            || $score < 4.0;

        $sells = Product::where('seller_id', $seller->id)
            ->where('status', 'active')
            ->whereNotNull('category_id')
            ->with('category:id,name')
            ->get()
            ->pluck('category.name')
            ->filter()
            ->unique()
            ->values()
            ->take(5);

        return [
            'seller_id'             => $seller->id,
            'username'              => $seller->username,
            'name'                  => $seller->name,
            'avatar_url'            => $seller->avatar_url,
            'is_verified'           => (bool) $seller->is_verified,
            'is_pro'                => $seller->hasActiveSubscription(),
            'joined_at'             => $seller->created_at,
            'trust_score'           => $score,
            'orders_completed'      => $totalOrdersAllTime,
            'avg_rating'            => $avgRating,
            'total_reviews'         => $totalReviews,
            'return_rate'           => $returnRate,
            'reports_30d'           => $reports30d,
            'reports_all_time'      => $reportsAllTime,
            'last_report_at'        => $lastReportAt,
            'off_platform_warnings' => $continuedWarnings,
            'sells'                 => $sells,
            'high_risk'             => $highRisk,
        ];
    }
}